### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by wonk4rol** [nnttoo/QT_SimpleKasir#1]
Tidak bisa download aplikasi windowsnya 

This site can’t be reachedgithub-production-release-asset-2e65be.s3.amazonaws.com took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_TIMED_OUT

**Comment by gvoze32** [comment]
Bisa bro, coba lagi

Ini linknya kalo belum tau
https://github.com/nnttoo/QT_SimpleKasir/releases/download/5.23.0.0/qtsimplekasir_v5_23_setup.exe

**Comment by wonk4rol** [comment]
ok, makasih bro, bisa!
