### ISSUE TITLE
Erorr bagian ekspor database

### ISSUE THREAD

**Issue by imamgembira** [nnttoo/QT_SimpleKasir#2]
mhn dibantu,, laptop menggunakan win 10, ms office 2010,,,
sdh melakukan langkah seperti video,,, namun pada bagian eksport database tidak bs menyimpan file backup nya,,,
rencana digunakan untuk tambah data barang agar bs di import database, sehingga cepat dalam penambahan data barang, trims,, kami tunggu respon nya.

**Comment by nnttoo** [comment]
dicoba masukan satu atau dua data barang terlebih dahulu di appsnya pak

**Comment by ilhamdrum** [comment]
selamat sore pak... klo di pasang costumer display suport ga pak yah?
